goalapp/config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :goals

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

goalapp/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

goalapp/app/models/user.rb
class User < ApplicationRecord
  validates :username, :session_token, :password_digest, presence: true
  validates :password, length: { minimum: 6, allow_nil: true }

  has_many :goals
  attr_reader :password

  after_initialize :ensure_session_token

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

  def ensure_session_token
    self.session_token ||= SecureRandom.urlsafe_base64
  end

  def reset_session_token!
    self.session_token = SecureRandom.urlsafe_base64
    self.save!
    self.session_token
  end

  def self.find_by_credentials(username, password)
    user = User.find_by(username: username)
    user && user.is_password?(password) ? user : nil
  end

end

goalapp/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  
  helper_method :logged_in?, :current_user
  
  def login(user)
    session[:session_token] = user.reset_session_token!
  end
  
  def logout
    current_user.reset_session_token!
    session[:session_token] = nil
  end
  
  def current_user
    @current_user ||= User.find_by(session_token: session[:session_token])
  end
  
  def logged_in?
    !!current_user
  end
  
  def ensure_login
    redirect_to new_session_url unless logged_in?
  end
  
  
end

goalapp/app/controllers/goals_controller.rb
class GoalsController < ApplicationController
  def index
    
  end

  def new
  end

  def create
  end

  def show
  end

  def edit
  end

  def update
  end

  def destroy
  end
end

goalapp/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  end

  def create
    @user = User.new(user_params)
    # debugger

    if @user.save
      login(@user) # to be defined in ApplicationController
      # # session[:session_token] = @user.reset_session_token!
      redirect_to goals_url
    else
      flash[:errors] = @user.errors.full_messages
      render :new
    end
  end

  def user_params
    params.require(:user).permit(:username, :password)
  end
end

goalapp/app/helpers/application_helper.rb
module ApplicationHelper
end

goalapp/app/helpers/goals_helper.rb
module GoalsHelper
end

goalapp/app/helpers/users_helper.rb
module UsersHelper
end

goalapp/app/views/goals/create.html.erb
<h1>Goals#create</h1>
<p>Find me in app/views/goals/create.html.erb</p>

goalapp/app/views/goals/destroy.html.erb
<h1>Goals#destroy</h1>
<p>Find me in app/views/goals/destroy.html.erb</p>

goalapp/app/views/goals/edit.html.erb
<h1>Goals#edit</h1>
<p>Find me in app/views/goals/edit.html.erb</p>

goalapp/app/views/goals/index.html.erb
<h1>Welcome <%= current_user %></h1>
<p>Find me in app/views/goals/index.html.erb</p>

goalapp/app/views/goals/new.html.erb
<h1>Goals#new</h1>
<p>Find me in app/views/goals/new.html.erb</p>

goalapp/app/views/goals/show.html.erb
<h1>Goals#show</h1>
<p>Find me in app/views/goals/show.html.erb</p>

goalapp/app/views/goals/update.html.erb
<h1>Goals#update</h1>
<p>Find me in app/views/goals/update.html.erb</p>

goalapp/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Goalapp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  
  <h1>Welcome <%= current_user %></h1>
  <%= 'Sign Out'  %>

  <body>
    <%= yield %>
  </body>
</html>

goalapp/app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

goalapp/app/views/users/new.html.erb
<h1>Sign Up</h1>
<form class="" action="<%= users_url %>" method="post">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  
  <label>Username
    <input type="text" name="user[username]" value="">
  </label>
  <label>Password
    <input type="password" name="user[password]" value="">
  </label>
  <input type="submit" name="" value="Sign Up">
  
  
</form>